### ISSUE TITLE
fix(ssl): automatic certificate renewal fails due to flawed container interaction

### ISSUE THREAD

**Issue by berntpopp** [berntpopp/vntyper-online-backend#25]
The SSL certificate for `vntyper.org` has expired and was not automatically renewed by the Certbot service. Manual rebuilds of the Docker containers did not resolve the issue, indicating a systemic architectural problem rather than a transient error.

### Root Cause Analysis

The failure is caused by several fundamental flaws in the container interaction and renewal logic:

1.  **Container Isolation Violation**: The `certbot` container's `entrypoint.sh` attempts to reload Nginx using a `--deploy-hook 'nginx -s reload'`. This command fails because the `nginx` process runs in the separate `proxy` container and is not accessible from the `certbot` container.
2.  **Race Condition on Startup**: The `certbot` container tries to acquire a certificate immediately upon starting, without waiting for the `proxy` container's web server to be fully initialized and ready to serve the ACME challenge. This can lead to validation failures.
3.  **Unreliable Renewal Mechanism**: The previous entrypoint script relied on a single execution pass and a `cron` job within the container, which is a fragile pattern. A persistent, long-running process is required for reliable renewal checks.
4.  **Fragile Persistence Model**: The use of host-path mounts for `/etc/letsencrypt` can lead to host permission issues and makes the setup less portable.

### Proposed Solution

To fix this permanently, we will refactor the architecture to a decoupled, event-driven model where each container has a single, clear responsibility.

-   **`certbot` Container**: Its sole responsibility is to acquire and renew certificates. It will run in a persistent loop, attempting renewal every 12 hours. It will no longer attempt to interact with Nginx.
-   **`proxy` Container**: It will be responsible for serving web traffic and reacting to certificate changes. It will start with a temporary HTTP-only config to handle the initial ACME challenge. It will then use `inotifywait` to monitor the shared certificate volume for changes and automatically reload its own configuration when a renewal occurs.

This creates a robust system where the proxy *observes* and *reacts* to changes made by the Certbot service, respecting container boundaries.

---

### Implementation Details

The following files will be updated to implement the new architecture.

<details>
<summary><strong>:floppy_disk: New `docker-compose.prod.yml`</strong></summary>

This version switches to Docker-managed named volumes for improved stability and portability.

```yaml
# docker-compose.prod.yml
services:
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: vntyper_proxy:2.0.0
    container_name: vntyper_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot_certs:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    env_file:
      - .env.production
    networks:
      - vntyper_network
    depends_on:
      - frontend
      - backend_api

  certbot:
    build:
      context: ./certbot
      dockerfile: Dockerfile
    container_name: vntyper_certbot
    volumes:
      - certbot_certs:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    env_file:
      - .env.production
    depends_on:
      - proxy

  # ... other services
  
networks:
  vntyper_network:
    driver: bridge

volumes:
  certbot_certs:
  certbot_www:
```
</details>

<details>
<summary><strong>:key: New `certbot/entrypoint.sh`</strong></summary>

This script simplifies the Certbot container's logic to focus only on certificate management.

```bash
#!/bin/sh
set -e

# Wait for proxy to be available, preventing a race condition
until nc -z proxy 80; do
    echo "Certbot is waiting for the proxy service to be ready..."
    sleep 5s & wait ${!}
done

# Standard certbot command to acquire/renew certs for both domains
certbot certonly \
    --webroot \
    -w /var/www/certbot \
    --email "${CERTBOT_EMAIL}" \
    -d "${SERVER_NAME}" -d "www.${SERVER_NAME}" \
    --rsa-key-size 4096 \
    --agree-tos \
    --non-interactive \
    --force-renewal \
    ${STAGING_ARG} # This will be --staging or empty based on env var

# Persistent renewal loop
echo "Certbot is starting the certificate renewal loop..."
while true; do
    sleep 12h & wait ${!}
    certbot renew --quiet
done
```
</details>

<details>
<summary><strong>:shield: New `proxy/entrypoint.sh`</strong></summary>

This script makes the Nginx container reactive and self-sufficient.

```bash
#!/bin/bash
set -e

CERT_PATH="/etc/letsencrypt/live/${SERVER_NAME}/fullchain.pem"

# Background function to wait for initial cert and switch to SSL config
wait_for_certs_and_switch_to_ssl() {
    while [ ! -f "$CERT_PATH" ]; do
        sleep 5s
    done
    envsubst '${SERVER_NAME} ${CLIENT_MAX_BODY_SIZE}' < /etc/nginx/conf.d/nginx.conf.template.ssl > /etc/nginx/conf.d/default.conf
    nginx -s reload
}

# Background function to monitor for renewals
monitor_cert_renewals() {
    while inotifywait -r -e create,modify /etc/letsencrypt/live; do
        nginx -s reload
    done
}

# Always start with ACME config to guarantee challenge success
envsubst '${SERVER_NAME} ${CLIENT_MAX_BODY_SIZE}' < /etc/nginx/conf.d/nginx.conf.template.acme > /etc/nginx/conf.d/default.conf

# Run monitors in the background
wait_for_certs_and_switch_to_ssl &
monitor_cert_renewals &

# Start Nginx in the foreground
exec nginx -g 'daemon off;'
```
</details>

### Definition of Done

-   [ ] All necessary files (`docker-compose.prod.yml`, `certbot/entrypoint.sh`, `proxy/entrypoint.sh`) are updated in the repository.
-   [ ] Upon deployment, a new valid SSL certificate is successfully acquired for `vntyper.org` and `www.vntyper.org`.
-   [ ] The `certbot` and `proxy` services run persistently without errors.
-   [ ] The system is capable of automatically renewing the certificate and reloading Nginx without any manual intervention.
