### ISSUE TITLE
Refactor: Externalize SSL Certificates and Optimize Renewal Workflow

### ISSUE THREAD

**Issue by berntpopp** [berntpopp/vntyper-online-backend#8]
### **Description**
Currently, SSL/TLS certificates are stored within the project repository, leading to issues with persistence across updates and potential security risks. Additionally, the workflow issues new certificates even when existing ones are valid, causing unnecessary renewals.

### **Proposed Changes**
1. **Externalize SSL Certificates:**
   - **Action:** Store certificates in a dedicated directory **outside** the project folder.
   - **Benefit:** Ensures certificate persistence across repository updates and enhances security by keeping sensitive files separate.

2. **Optimize Certificate Renewal:**
   - **Action:** Modify the workflow to check for existing valid certificates before issuing new ones.
   - **Benefit:** Prevents unnecessary certificate renewals, reducing load on certificate authorities and avoiding potential rate limits.

### **Implementation Steps**
1. **Create External Certificate Directory:**
   - Choose a secure path on the host machine (e.g., `/etc/ssl/certs/vntyper`).

2. **Update `docker-compose.yml`:**
   ```yaml
   services:
     proxy:
       image: nginx:latest
       volumes:
         - /etc/ssl/certs/vntyper:/etc/letsencrypt
         - /var/www/certbot:/var/www/certbot
         - ./nginx.conf:/etc/nginx/nginx.conf
       ports:
         - "80:80"
         - "443:443"
       restart: unless-stopped
   ```

3. **Modify Certificate Issuance Script:**
   - Add checks to verify existing certificates' validity before renewal.
   - Example using Certbot:
     ```bash
     if certbot certificates | grep -q "VALID"; then
       echo "Certificates are still valid. Skipping renewal."
     else
       certbot renew --deploy-hook "nginx -s reload"
     fi
     ```

4. **Adjust Nginx Configuration:**
   - Ensure Nginx references certificates from the external directory.
   - Example:
     ```nginx
     ssl_certificate /etc/letsencrypt/live/yourdomain.com/fullchain.pem;
     ssl_certificate_key /etc/letsencrypt/live/yourdomain.com/privkey.pem;
     ```

5. **Update Documentation:**
   - Document the new certificate storage path and renewal process for future reference.

### **Benefits**
- **Persistence:** Certificates remain intact across updates and deployments.
- **Security:** Reduces risk of exposing sensitive certificate files within the repository.
- **Efficiency:** Avoids unnecessary certificate renewals, optimizing resource usage.
